Feature/hw2
rifatko32/console-packages pull request #2
Opened 2024-12-24 05:56 UTC by rifatko32

2024-12-24 18:32 UTC, vbnz34343434 requested changes

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +    private final static Integer DEFAULT_TRUCK_COUNT = 10;
Код "не отранжирован" - константы по-умолчанию должны быть выше (можно нажать `Ctrl+Alt+Shift+L` и поставить галочку `Rearrange code`, либо такие же настройки есть в вкладке коммита)

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +    private void executePlaceCommand(
вот эти методы - `executePlaceCommand` и `executeTruckReadingCommand` стоит как-то вынести в отдельные классы, кажется что выполнять сам алгоритм команды не очень правильно внутри приватного метода. Туда же стоит каким-то образом вынести соотв. регурялки, чтобы здесь был вызов какой-то абстрактной команды, а выбор какой - стоял за самими классами-командами

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +    private void writeReportToFile(PackagePlaceStringReport report) {
тут тоже метод не на своем месте. Публичные методы должны быть наверху

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +        if (report == null || report.getReportStrings().isEmpty()) {
вот тут ты че-т загнался немного - у тебя точно такая же проверка есть выше по стеку вызовов - в публичном `writeReport(PackagePlaceStringReport report)`

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +        writeReportToFile(report);
если честно, не особо понял идею оставить именно этот код в публичном методе, а вот весь остальной код в приватном. Я б наоборот, вынес только try/catch в отдельный метод и тогда публичный содержал бы только проверку и название файла

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/util/TruckJsonFileReader.java
> +            trucks = gson.fromJson(br, new TypeToken<List<Truck>>() {}.getType());
если ты здесь будешь сразу возвращать значение, то переменная `trucks` тебе будет не нужна

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/util/TruckJsonFileReader.java
> +        var gson = new Gson();
думаю это стоит вынести в поле класса и заполнять через DI

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/truck/TruckUnloadingReportEngine.java
> +    PackagePlaceStringReport generateReport(List<ru.hofftech.consolepackages.service.packageitem.Package> packages);
о, а чего тут импорт не используется и дальше в реализациях?

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/truck/impl/TruckUnloadingStringReportEngine.java
> +        if (packages.isEmpty()) {
в целом эта проверка не нужна, цикл просто нге запустится и вернется тот же report

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/report/truck/impl/TruckUnloadingStringReportEngine.java
> +    private final static String PACKAGE_DELIMITER = System.lineSeparator();
о, правильно, что используешь системный разделитель

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/truck/Truck.java
> +    @Getter
вот из-за этого геттера тебе идея подсказывает на Truck'e, что можно просто над классом указать, если для всех полей нужен геттер

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/SinglePackagePerTruckPlaceAlgorithm.java
>      private final int TRUCK_BACK_HEIGHT = 6;
немного странно, что эти константу у тебя в трех разных алгоритмах объявлены. Я б куда-нить в отдельный класс эти константы положил - это неплохая практика (как будто класс с настройками приложения)

2024-12-24 18:32 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/EqualDistributionPlaceAlgorithm.java
> +                // packageItem.setPlaced(true);
по-хорошему закомменченого кода в гите не должно быть

2024-12-24 18:32 UTC, vbnz34343434 commented on src/test/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/PackagePlaceJsonReportEngineTest.java
> +        assertThat(report.getReportStrings()).isNotEmpty();
не очень конечно много всего тут проверяется)

2024-12-24 18:32 UTC, vbnz34343434 commented on src/test/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/PackagePlaceJsonReportEngineTest.java
> +public class PackagePlaceJsonReportEngineTest {
вот этот тест-класс не доехал до нового пакета после рефаторинга походу

2024-12-25 05:38 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +    private final static Integer DEFAULT_TRUCK_COUNT = 10;
поправил

2024-12-25 05:38 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +    private void writeReportToFile(PackagePlaceStringReport report) {
поправил

2024-12-25 05:38 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +        if (report == null || report.getReportStrings().isEmpty()) {
убрал

2024-12-25 05:40 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/report/outputchannel/impl/ReportToFileWriter.java
> +        writeReportToFile(report);
перенес

2024-12-25 05:42 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/util/TruckJsonFileReader.java
> +            trucks = gson.fromJson(br, new TypeToken<List<Truck>>() {}.getType());
переделал

2024-12-25 05:44 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/util/TruckJsonFileReader.java
> +        var gson = new Gson();
вынес

2024-12-25 05:45 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/report/truck/impl/TruckUnloadingStringReportEngine.java
> +        if (packages.isEmpty()) {
убрал

2024-12-25 05:48 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/truck/Truck.java
> +    @Getter
сделал

2024-12-25 05:50 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/SinglePackagePerTruckPlaceAlgorithm.java
>      private final int TRUCK_BACK_HEIGHT = 6;
вынес

2024-12-25 05:51 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/EqualDistributionPlaceAlgorithm.java
> +                // packageItem.setPlaced(true);
почистил

2024-12-25 05:53 UTC, rifatko32 commented on src/test/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/PackagePlaceJsonReportEngineTest.java
> +        assertThat(report.getReportStrings()).isNotEmpty();
проверка на null лишняя - убрал

2024-12-25 05:55 UTC, rifatko32 commented on src/test/java/ru/hofftech/consolepackages/service/packageitem/engine/impl/PackagePlaceJsonReportEngineTest.java
> +public class PackagePlaceJsonReportEngineTest {
перенес в соотв. пакет

2024-12-25 10:12 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +    private void executePlaceCommand(
переделал на паттерн команда

2024-12-25 19:22 UTC, vbnz34343434 requested changes

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/command/impl/PlacePackagesFromTxtFileToConsoleCommand.java
> +    private final String strCommand;
вот здесь опять добавил состояние классу, стоит перенести как входной агрумент `execute()` иначе будут проблемки при переводе приложения на spring

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandFactory.java
> +        if (EXIT_COMMAND.equals(strCommand)) {
вот это как будто лишнее, наверн забыл убрать. В CommandParcer'e уже есть про эту команду

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandParser.java
> +            case CommandConstants.EQUAL_ALGORITHM_NAME -> PackagePlaceAlgorithmType.EQUAL_DISTRIBUTION;
вот эту штуку кажется забыл исправить. switch не нужен, если добавишь в енам одно поле (значения которого указаны в константах) и по нему будешь искать значение

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandParser.java
> +    public static PackagePlaceAlgorithmType readAlgorithmName(String strCommand) {
понимаю что эти методы - readTruckCount, readAlgorithmName, readFilePath это парсинг команды, но как будто они должны лежать где-то в рамках выполнения конкретной команды. Понимаю что у них есть и общие части и поэтому ты их захотел вынести в отдельный класс (но возможно эти общие части слишком общие и может стоит тогда объединить команды? и в таком случае команды будут различаться только одним параметром - как вернуть ответ, либо в json писаться будет просто допом к выводу к консоль)

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandParser.java
> +        Matcher matcher;
как будто переменная не нужна и можно в switch'e сразу возвращать значения

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +                log.error("Error while executing command: {}", e);
наверн просто опечатался - для исключения в log.error заготовлено свое место и его не надо добавлять в текст лога, с помощью {}

2024-12-25 19:22 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +                command.execute();
ваще чисто и красиво тут стало, мне оч нравится

2024-12-26 13:33 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/command/impl/PlacePackagesFromTxtFileToConsoleCommand.java
> +    private final String strCommand;
договорились оставить так

2024-12-26 13:33 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandFactory.java
> +        if (EXIT_COMMAND.equals(strCommand)) {
убрал

2024-12-26 13:40 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandParser.java
> +        Matcher matcher;
переделал

2024-12-26 13:41 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/controller/ConsoleController.java
> +                log.error("Error while executing command: {}", e);
почистил

2024-12-26 13:49 UTC, rifatko32 commented on src/main/java/ru/hofftech/consolepackages/service/command/CommandParser.java
> +            case CommandConstants.EQUAL_ALGORITHM_NAME -> PackagePlaceAlgorithmType.EQUAL_DISTRIBUTION;
поправил

2024-12-26 18:38 UTC, vbnz34343434 approved these changes
Принято

2024-12-26 18:38 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/PackagePlaceAlgorithmType.java
> +    public static PackagePlaceAlgorithmType fromConsoleValue(String consoleValue) {
поле-то добавил, но вот забыл его использовать)

2024-12-26 18:38 UTC, vbnz34343434 commented on src/main/java/ru/hofftech/consolepackages/service/packageitem/engine/PackagePlaceAlgorithmType.java
> +        for (PackagePlaceAlgorithmType algorithmType : PackagePlaceAlgorithmType.values()) {
обычно когда используют поле в енаме и понимают, что будет нужно сделать метод получения по значению - делают статичную мапу, где ключом становится fieldValue, а значением Enum.name(), чтоб она на этапе загрузки статики появилась в памяти, после чего делают  метод, который по ключу возвращает необходимый name() енама (вот так https://www.baeldung.com/java-enum-values#caching). У тебя сложность в том, что ты хочешь чтоб ключ был регистронезависимый. Для этого есть простое решение - https://www.baeldung.com/java-map-with-case-insensitive-keys#treemap

2024-12-27 10:28 UTC, merged